version: "3.8"
services:
  go:
    container_name: app
    volumes:
      - ./:/project/
    working_dir: /project
    tty: true
    build:
      context: .
      dockerfile: app.dockerfile
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy
    command: sh -c 'go mod tidy && air'

  db:
    container_name: db
    build:
      context: .
      dockerfile: db.dockerfile
    tty: true
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: "test"
      MYSQL_USER: "tester"
      MYSQL_PASSWORD: "password"
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "--password=root",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - type: volume
        source: mysql_data
        target: /var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - default

networks:
  default:
volumes:
  mysql_data:
